service: graphql-aws
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true
functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
