service: graphql-aws

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true

plugins:
  - serverless-offline

functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
